import pandas as pd
import pandas_ta as ta

class TechnicalAnalysisAgent:
    """
    Agent responsible for performing technical analysis on stock data.
    """
    def analyze(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Analyzes the stock data and adds technical indicators.

        Args:
            data (pd.DataFrame): The historical stock data.

        Returns:
            pd.DataFrame: The data with added technical indicators.
        """
        if data.empty:
            return data

        # Calculate RSI
        data.ta.rsi(append=True)

        # Calculate MACD
        data.ta.macd(append=True)

        # Calculate Simple Moving Averages (SMA)
        data.ta.sma(length=20, append=True)
        data.ta.sma(length=50, append=True)

        # Remove rows with NaN values that are generated by the indicators
        data.dropna(inplace=True)

        return data
